// Copyright (c) STORM REMOTE CONTROL Contributors. All rights reserved.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using StormRemoteControl.Models;

namespace StormRemoteControl.Services
{
    /// <summary>
    /// Complete localization service supporting 6 standard STORM SOFT languages:
    /// Russian (RU), English (EN), German (DE), French (FR), Chinese (ZH), Japanese (JA).
    /// Supports dynamic switching on the fly without application restart.
    /// </summary>
    public static class LocalizationService
    {
        public static event Action? LanguageChanged;

        private static string _currentLanguage = "ru";

        public static string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value && SupportedLanguages.ContainsKey(value))
                {
                    _currentLanguage = value;
                    AppSettings.ActiveLanguage = value;
                    AppSettings.Save();
                    LanguageChanged?.Invoke();
                }
            }
        }

        public static readonly Dictionary<string, (string Name, string NativeName, string Flag)> SupportedLanguages = new()
        {
            { "ru", ("Русский", "Русский", "🇷🇺") },
            { "en", ("English", "English", "🇬🇧") },
            { "de", ("German", "Deutsch", "🇩🇪") },
            { "fr", ("French", "Français", "🇫🇷") },
            { "zh", ("Chinese", "中文", "🇨🇳") },
            { "ja", ("Japanese", "日本語", "🇯🇵") }
        };

        private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
        {
            ["ru"] = new()
            {
                // Title & Shell
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "Файлы",
                ["Settings"] = "Настройки",
                ["Info"] = "Информация",
                ["StatusInitializing"] = "Инициализация...",
                ["StatusOnline"] = "Сеть: онлайн",
                ["StatusOffline"] = "Сеть: офлайн",
                ["StatusLocal"] = "Сеть: локальная",
                ["StatusNoInternet"] = "Сеть: нет интернета",
                ["StatusUndetermined"] = "Сеть: не определено",
                
                // Main Page - Host
                ["YourComputer"] = "Ваш компьютер",
                ["StatusReady"] = "Готов",
                ["StatusStarting"] = "Запуск...",
                ["StatusActive"] = "Активен",
                ["StatusWaiting"] = "Ожидание...",
                ["StatusConnected"] = "Подключён",
                ["StatusDisconnected"] = "Отключён",
                ["StatusErrorRetry"] = "Ошибка, повтор...",
                ["HostDescription"] = "Ваш уникальный ID для подключения. Передайте его партнеру.",
                ["YourId"] = "Ваш ID",
                ["ProtectedByPassword"] = "Защищено паролем",
                ["CopyId"] = "Копировать ID",
                ["ChangeId"] = "Сменить ID",
                
                // Main Page - Client
                ["RemoteControl"] = "Удаленное управление",
                ["ClientDescription"] = "Введите ID удалённого компьютера для подключения через зашифрованный P2P-канал.",
                ["PartnerIdPlaceholder"] = "Введите ID партнера (Например, 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "Пароль (если установлен)",
                ["Connect"] = "Подключиться",
                
                // Main Page - Recent Connections
                ["RecentConnections"] = "Недавние подключения",
                ["NoRecentConnections"] = "Нет недавних подключений",
                ["RecentConnectionsDesc"] = "После первого успешного подключения оно отобразится здесь.",
                
                // Settings Dialog
                ["SettingsTitle"] = "Настройки",
                ["SectionConnection"] = "Подключение",
                ["SectionVideo"] = "Видео",
                ["SectionSecurity"] = "Безопасность",
                ["SectionAppearance"] = "Оформление и язык",
                ["SectionAbout"] = "О программе",
                ["ConnectionProfile"] = "Профиль подключения",
                ["ProfilePerf"] = "Производительность",
                ["ProfileBalance"] = "Баланс",
                ["ProfileQuality"] = "Качество",
                ["Port"] = "Порт",
                ["ConnectionPassword"] = "Пароль подключения",
                ["PasswordNotSet"] = "Не задан",
                ["SignalingUrl"] = "Адрес сигнального сервера",
                ["CaptureMonitor"] = "Монитор для захвата",
                ["MonitorPrimary"] = "(Основной)",
                ["MaxFps"] = "Макс. FPS",
                ["MaxResolution"] = "Макс. разрешение",
                ["ResNative"] = "Нативное",
                ["Encryption"] = "Шифрование",
                ["RequireConfirmation"] = "Подтверждение подключения",
                ["AppTheme"] = "Тема оформления",
                ["AppLanguage"] = "Язык интерфейса",
                ["Save"] = "Сохранить",
                ["Cancel"] = "Отмена",
                ["ToggleOn"] = "Вкл",
                ["ToggleOff"] = "Выкл",
                
                // Technology Info
                ["TechInfoTitle"] = "Информация о технологиях",
                ["Close"] = "Закрыть",
                ["SecEncryption"] = "Шифрование",
                ["SecNat"] = "Обход NAT (NAT Traversal)",
                ["SecVideoStream"] = "Видеопоток",
                ["SecNetwork"] = "Сеть и протокол",
                ["SecFeatures"] = "Возможности",
                
                // Dialogs & Messages
                ["DialogAlreadyRunningTitle"] = "Приложение уже запущено",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROL уже работает в одном экземпляре. Окно активировано.",
                ["DialogChangeIdTitle"] = "Сменить ID",
                ["DialogChangeIdContent"] = "Вы уверены? Текущий ID будет заменён на новый случайный. Все, кто знает ваш текущий ID, не смогут подключиться.",
                ["DialogIncomingConnTitle"] = "Входящее подключение",
                ["DialogIncomingConnContent"] = "К вашему компьютеру успешно подключился партнер. Теперь он видит ваш экран и может управлять им.",
                ["ErrorInvalidId"] = "Некорректный ID",
                ["ErrorInvalidIdContent"] = "Введите ID удалённого компьютера.",
                ["ErrorConnection"] = "Ошибка подключения",
                ["ErrorConnectionContent"] = "Не удалось установить P2P-соединение. Проверьте ID, активность хоста и подключение к сети.",
                ["ErrorNetwork"] = "Сетевая ошибка",
                
                // Tray Menu
                ["TrayRestore"] = "Развернуть",
                ["TrayExit"] = "Выход",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "Приложение свёрнуто в системный трей. Кликните по значку для восстановления.",
                
                // File Manager & Session
                ["FileManagerTitle"] = "Файловый менеджер",
                ["LocalPc"] = "Локальный ПК",
                ["RemotePc"] = "Удалённый ПК",
                ["RemotePcNotConnected"] = "Удалённый ПК не подключён",
                ["RemotePcConnectHint"] = "Подключитесь к удалённому ПК для доступа к файлам.",
                ["ColName"] = "Имя",
                ["ColSize"] = "Размер",
                ["ColModified"] = "Изменён",
                ["SecureChat"] = "Защищённый чат",
                ["ChatPlaceholder"] = "Сообщение...",
                ["Send"] = "Отпр.",
                ["SpeedQuality"] = "Качество",
                ["Hotkeys"] = "Горячие клавиши",
                ["AudioToggle"] = "Звук: вкл",
                ["Chat"] = "Чат",
                ["Disconnect"] = "Закрыть",
                ["SendFile"] = "Отправить файл...",
                ["F3View"] = "F3 Просмотр",
                ["F5Copy"] = "F5 Копировать",
                ["F6Move"] = "F6 Переместить",
                ["F7NewFolder"] = "F7 Создать папку",
                ["F8Delete"] = "F8 Удалить",
                ["F9Rename"] = "F9 Переименовать",
                ["CtrlRRefresh"] = "Ctrl+R Обновить"
            },
            ["en"] = new()
            {
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "Files",
                ["Settings"] = "Settings",
                ["Info"] = "Information",
                ["StatusInitializing"] = "Initializing...",
                ["StatusOnline"] = "Network: online",
                ["StatusOffline"] = "Network: offline",
                ["StatusLocal"] = "Network: local",
                ["StatusNoInternet"] = "Network: no internet",
                ["StatusUndetermined"] = "Network: undetermined",
                
                ["YourComputer"] = "Your computer",
                ["StatusReady"] = "Ready",
                ["StatusStarting"] = "Starting...",
                ["StatusActive"] = "Active",
                ["StatusWaiting"] = "Waiting...",
                ["StatusConnected"] = "Connected",
                ["StatusDisconnected"] = "Disconnected",
                ["StatusErrorRetry"] = "Error, retrying...",
                ["HostDescription"] = "Your unique ID for remote connection. Share it with your partner.",
                ["YourId"] = "Your ID",
                ["ProtectedByPassword"] = "Password protected",
                ["CopyId"] = "Copy ID",
                ["ChangeId"] = "Change ID",
                
                ["RemoteControl"] = "Remote control",
                ["ClientDescription"] = "Enter remote computer ID to connect via encrypted P2P channel.",
                ["PartnerIdPlaceholder"] = "Enter partner ID (e.g. 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "Password (if set)",
                ["Connect"] = "Connect",
                
                ["RecentConnections"] = "Recent connections",
                ["NoRecentConnections"] = "No recent connections",
                ["RecentConnectionsDesc"] = "After your first successful connection, it will appear here.",
                
                ["SettingsTitle"] = "Settings",
                ["SectionConnection"] = "Connection",
                ["SectionVideo"] = "Video",
                ["SectionSecurity"] = "Security",
                ["SectionAppearance"] = "Appearance and language",
                ["SectionAbout"] = "About",
                ["ConnectionProfile"] = "Connection profile",
                ["ProfilePerf"] = "Performance",
                ["ProfileBalance"] = "Balanced",
                ["ProfileQuality"] = "Quality",
                ["Port"] = "Port",
                ["ConnectionPassword"] = "Connection password",
                ["PasswordNotSet"] = "Not set",
                ["SignalingUrl"] = "Signaling server URL",
                ["CaptureMonitor"] = "Capture monitor",
                ["MonitorPrimary"] = "(Primary)",
                ["MaxFps"] = "Max FPS",
                ["MaxResolution"] = "Max resolution",
                ["ResNative"] = "Native",
                ["Encryption"] = "Encryption",
                ["RequireConfirmation"] = "Require confirmation",
                ["AppTheme"] = "Visual theme",
                ["AppLanguage"] = "Interface language",
                ["Save"] = "Save",
                ["Cancel"] = "Cancel",
                ["ToggleOn"] = "On",
                ["ToggleOff"] = "Off",
                
                ["TechInfoTitle"] = "Technology information",
                ["Close"] = "Close",
                ["SecEncryption"] = "Encryption",
                ["SecNat"] = "NAT Traversal (STUN / UDP)",
                ["SecVideoStream"] = "Video stream",
                ["SecNetwork"] = "Network and protocol",
                ["SecFeatures"] = "Features",
                
                ["DialogAlreadyRunningTitle"] = "Application already running",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROL is already running in a single instance. Window activated.",
                ["DialogChangeIdTitle"] = "Change ID",
                ["DialogChangeIdContent"] = "Are you sure? Your ID will be regenerated and previous partners will lose access.",
                ["DialogIncomingConnTitle"] = "Incoming connection",
                ["DialogIncomingConnContent"] = "A partner has connected to your PC. They can now view and control your desktop.",
                ["ErrorInvalidId"] = "Invalid ID",
                ["ErrorInvalidIdContent"] = "Please enter a valid remote computer ID.",
                ["ErrorConnection"] = "Connection error",
                ["ErrorConnectionContent"] = "Could not establish P2P connection. Verify the ID, host status, and network.",
                ["ErrorNetwork"] = "Network error",
                
                ["TrayRestore"] = "Restore",
                ["TrayExit"] = "Exit",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "Application minimized to system tray. Click icon to restore.",
                
                ["FileManagerTitle"] = "File manager",
                ["LocalPc"] = "Local PC",
                ["RemotePc"] = "Remote PC",
                ["RemotePcNotConnected"] = "Remote PC not connected",
                ["RemotePcConnectHint"] = "Connect to a remote PC to access files.",
                ["ColName"] = "Name",
                ["ColSize"] = "Size",
                ["ColModified"] = "Modified",
                ["SecureChat"] = "Secure chat",
                ["ChatPlaceholder"] = "Message...",
                ["Send"] = "Send",
                ["SpeedQuality"] = "Quality",
                ["Hotkeys"] = "Hotkeys",
                ["AudioToggle"] = "Audio: on",
                ["Chat"] = "Chat",
                ["Disconnect"] = "Close",
                ["SendFile"] = "Send file...",
                ["F3View"] = "F3 View",
                ["F5Copy"] = "F5 Copy",
                ["F6Move"] = "F6 Move",
                ["F7NewFolder"] = "F7 New folder",
                ["F8Delete"] = "F8 Delete",
                ["F9Rename"] = "F9 Rename",
                ["CtrlRRefresh"] = "Ctrl+R Refresh"
            },
            ["de"] = new()
            {
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "Dateien",
                ["Settings"] = "Einstellungen",
                ["Info"] = "Information",
                ["StatusInitializing"] = "Initialisierung...",
                ["StatusOnline"] = "Netzwerk: online",
                ["StatusOffline"] = "Netzwerk: offline",
                ["StatusLocal"] = "Netzwerk: lokal",
                ["StatusNoInternet"] = "Netzwerk: kein Internet",
                ["StatusUndetermined"] = "Netzwerk: unbestimmt",
                
                ["YourComputer"] = "Ihr Computer",
                ["StatusReady"] = "Bereit",
                ["StatusStarting"] = "Starten...",
                ["StatusActive"] = "Aktiv",
                ["StatusWaiting"] = "Warten...",
                ["StatusConnected"] = "Verbunden",
                ["StatusDisconnected"] = "Getrennt",
                ["StatusErrorRetry"] = "Fehler, Wiederholung...",
                ["HostDescription"] = "Ihre eindeutige ID für die Fernverbindung. Teilen Sie sie mit Ihrem Partner.",
                ["YourId"] = "Ihre ID",
                ["ProtectedByPassword"] = "Passwortgeschützt",
                ["CopyId"] = "ID kopieren",
                ["ChangeId"] = "ID ändern",
                
                ["RemoteControl"] = "Fernsteuerung",
                ["ClientDescription"] = "Geben Sie die ID des entfernten Computers ein, um eine verschlüsselte P2P-Verbindung herzustellen.",
                ["PartnerIdPlaceholder"] = "Partner-ID eingeben (z. B. 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "Passwort (falls festgelegt)",
                ["Connect"] = "Verbinden",
                
                ["RecentConnections"] = "Letzte Verbindungen",
                ["NoRecentConnections"] = "Keine letzten Verbindungen",
                ["RecentConnectionsDesc"] = "Nach der ersten erfolgreichen Verbindung wird diese hier angezeigt.",
                
                ["SettingsTitle"] = "Einstellungen",
                ["SectionConnection"] = "Verbindung",
                ["SectionVideo"] = "Video",
                ["SectionSecurity"] = "Sicherheit",
                ["SectionAppearance"] = "Erscheinungsbild und Sprache",
                ["SectionAbout"] = "Über die Anwendung",
                ["ConnectionProfile"] = "Verbindungsprofil",
                ["ProfilePerf"] = "Leistung",
                ["ProfileBalance"] = "Ausgewogen",
                ["ProfileQuality"] = "Qualität",
                ["Port"] = "Port",
                ["ConnectionPassword"] = "Verbindungspasswort",
                ["PasswordNotSet"] = "Nicht festgelegt",
                ["SignalingUrl"] = "Signalisierungsserver-Adresse",
                ["CaptureMonitor"] = "Aufnahmemonitor",
                ["MonitorPrimary"] = "(Hauptmonitor)",
                ["MaxFps"] = "Max. FPS",
                ["MaxResolution"] = "Max. Auflösung",
                ["ResNative"] = "Nativ",
                ["Encryption"] = "Verschlüsselung",
                ["RequireConfirmation"] = "Bestätigung anfordern",
                ["AppTheme"] = "Farbschema",
                ["AppLanguage"] = "Sprache",
                ["Save"] = "Speichern",
                ["Cancel"] = "Abbrechen",
                ["ToggleOn"] = "Ein",
                ["ToggleOff"] = "Aus",
                
                ["TechInfoTitle"] = "Technologie-Informationen",
                ["Close"] = "Schließen",
                ["SecEncryption"] = "Verschlüsselung",
                ["SecNat"] = "NAT-Traversal (STUN / UDP)",
                ["SecVideoStream"] = "Videostream",
                ["SecNetwork"] = "Netzwerk und Protokoll",
                ["SecFeatures"] = "Funktionen",
                
                ["DialogAlreadyRunningTitle"] = "Anwendung läuft bereits",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROL läuft bereits in einer einzigen Instanz. Fenster aktiviert.",
                ["DialogChangeIdTitle"] = "ID ändern",
                ["DialogChangeIdContent"] = "Sind Sie sicher? Ihre ID wird neu generiert.",
                ["DialogIncomingConnTitle"] = "Eingehende Verbindung",
                ["DialogIncomingConnContent"] = "Ein Partner hat sich erfolgreich mit Ihrem PC verbunden.",
                ["ErrorInvalidId"] = "Ungültige ID",
                ["ErrorInvalidIdContent"] = "Bitte geben Sie eine gültige ID ein.",
                ["ErrorConnection"] = "Verbindungsfehler",
                ["ErrorConnectionContent"] = "P2P-Verbindung konnte nicht hergestellt werden.",
                ["ErrorNetwork"] = "Netzwerkfehler",
                
                ["TrayRestore"] = "Wiederherstellen",
                ["TrayExit"] = "Beenden",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "Anwendung im Infobereich minimiert.",
                
                ["FileManagerTitle"] = "Dateimanager",
                ["LocalPc"] = "Lokaler PC",
                ["RemotePc"] = "Entfernter PC",
                ["RemotePcNotConnected"] = "Entfernter PC nicht verbunden",
                ["RemotePcConnectHint"] = "Verbinden Sie sich mit einem entfernten PC, um auf Dateien zuzugreifen.",
                ["ColName"] = "Name",
                ["ColSize"] = "Größe",
                ["ColModified"] = "Geändert",
                ["SecureChat"] = "Sicherer Chat",
                ["ChatPlaceholder"] = "Nachricht...",
                ["Send"] = "Senden",
                ["SpeedQuality"] = "Qualität",
                ["Hotkeys"] = "Tastenkombinationen",
                ["AudioToggle"] = "Audio: ein",
                ["Chat"] = "Chat",
                ["Disconnect"] = "Schließen",
                ["SendFile"] = "Datei senden...",
                ["F3View"] = "F3 Anzeigen",
                ["F5Copy"] = "F5 Kopieren",
                ["F6Move"] = "F6 Verschieben",
                ["F7NewFolder"] = "F7 Neuer Ordner",
                ["F8Delete"] = "F8 Löschen",
                ["F9Rename"] = "F9 Umbenennen",
                ["CtrlRRefresh"] = "Ctrl+R Aktualisieren"
            },
            ["fr"] = new()
            {
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "Fichiers",
                ["Settings"] = "Paramètres",
                ["Info"] = "Information",
                ["StatusInitializing"] = "Initialisation...",
                ["StatusOnline"] = "Réseau: en ligne",
                ["StatusOffline"] = "Réseau: hors ligne",
                ["StatusLocal"] = "Réseau: local",
                ["StatusNoInternet"] = "Réseau: pas d'internet",
                ["StatusUndetermined"] = "Réseau: indéterminé",
                
                ["YourComputer"] = "Votre ordinateur",
                ["StatusReady"] = "Prêt",
                ["StatusStarting"] = "Démarrage...",
                ["StatusActive"] = "Actif",
                ["StatusWaiting"] = "En attente...",
                ["StatusConnected"] = "Connecté",
                ["StatusDisconnected"] = "Déconnecté",
                ["StatusErrorRetry"] = "Erreur, nouvelle tentative...",
                ["HostDescription"] = "Votre identifiant unique de connexion. Partagez-le avec votre partenaire.",
                ["YourId"] = "Votre ID",
                ["ProtectedByPassword"] = "Protégé par mot de passe",
                ["CopyId"] = "Copier l'ID",
                ["ChangeId"] = "Changer l'ID",
                
                ["RemoteControl"] = "Contrôle à distance",
                ["ClientDescription"] = "Entrez l'ID de l'ordinateur distant pour vous connecter via un canal P2P chiffré.",
                ["PartnerIdPlaceholder"] = "Entrez l'ID du partenaire (ex. 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "Mot de passe (si configuré)",
                ["Connect"] = "Se connecter",
                
                ["RecentConnections"] = "Connexions récentes",
                ["NoRecentConnections"] = "Aucune connexion récente",
                ["RecentConnectionsDesc"] = "Après votre première connexion réussie, elle apparaîtra ici.",
                
                ["SettingsTitle"] = "Paramètres",
                ["SectionConnection"] = "Connexion",
                ["SectionVideo"] = "Vidéo",
                ["SectionSecurity"] = "Sécurité",
                ["SectionAppearance"] = "Apparence et langue",
                ["SectionAbout"] = "À propos",
                ["ConnectionProfile"] = "Profil de connexion",
                ["ProfilePerf"] = "Performance",
                ["ProfileBalance"] = "Équilibré",
                ["ProfileQuality"] = "Qualité",
                ["Port"] = "Port",
                ["ConnectionPassword"] = "Mot de passe de connexion",
                ["PasswordNotSet"] = "Non défini",
                ["SignalingUrl"] = "URL du serveur de signalisation",
                ["CaptureMonitor"] = "Écran de capture",
                ["MonitorPrimary"] = "(Principal)",
                ["MaxFps"] = "FPS max.",
                ["MaxResolution"] = "Résolution max.",
                ["ResNative"] = "Natif",
                ["Encryption"] = "Chiffrement",
                ["RequireConfirmation"] = "Exiger une confirmation",
                ["AppTheme"] = "Thème visuel",
                ["AppLanguage"] = "Langue",
                ["Save"] = "Enregistrer",
                ["Cancel"] = "Annuler",
                ["ToggleOn"] = "Activé",
                ["ToggleOff"] = "Désactivé",
                
                ["TechInfoTitle"] = "Informations techniques",
                ["Close"] = "Fermer",
                ["SecEncryption"] = "Chiffrement",
                ["SecNat"] = "Traversée NAT (STUN / UDP)",
                ["SecVideoStream"] = "Flux vidéo",
                ["SecNetwork"] = "Réseau et protocole",
                ["SecFeatures"] = "Fonctionnalités",
                
                ["DialogAlreadyRunningTitle"] = "Application déjà en cours d'exécution",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROL s'exécute déjà en instance unique. Fenêtre activée.",
                ["DialogChangeIdTitle"] = "Changer l'ID",
                ["DialogChangeIdContent"] = "Êtes-vous sûr ? Votre ID actuel sera remplacé par un nouvel identifiant aléatoire.",
                ["DialogIncomingConnTitle"] = "Connexion entrante",
                ["DialogIncomingConnContent"] = "Un partenaire s'est connecté avec succès à votre PC.",
                ["ErrorInvalidId"] = "ID invalide",
                ["ErrorInvalidIdContent"] = "Veuillez saisir un ID valide.",
                ["ErrorConnection"] = "Erreur de connexion",
                ["ErrorConnectionContent"] = "Impossible d'établir la connexion P2P.",
                ["ErrorNetwork"] = "Erreur réseau",
                
                ["TrayRestore"] = "Restaurer",
                ["TrayExit"] = "Quitter",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "Application réduite dans la barre d'état système.",
                
                ["FileManagerTitle"] = "Gestionnaire de fichiers",
                ["LocalPc"] = "PC local",
                ["RemotePc"] = "PC distant",
                ["RemotePcNotConnected"] = "PC distant non connecté",
                ["RemotePcConnectHint"] = "Connectez-vous à un PC distant pour accéder aux fichiers.",
                ["ColName"] = "Nom",
                ["ColSize"] = "Taille",
                ["ColModified"] = "Modifié",
                ["SecureChat"] = "Chat sécurisé",
                ["ChatPlaceholder"] = "Message...",
                ["Send"] = "Envoyer",
                ["SpeedQuality"] = "Qualité",
                ["Hotkeys"] = "Raccourcis",
                ["AudioToggle"] = "Audio: activé",
                ["Chat"] = "Chat",
                ["Disconnect"] = "Fermer",
                ["SendFile"] = "Envoyer un fichier...",
                ["F3View"] = "F3 Afficher",
                ["F5Copy"] = "F5 Copier",
                ["F6Move"] = "F6 Déplacer",
                ["F7NewFolder"] = "F7 Nouveau dossier",
                ["F8Delete"] = "F8 Supprimer",
                ["F9Rename"] = "F9 Renommer",
                ["CtrlRRefresh"] = "Ctrl+R Actualiser"
            },
            ["zh"] = new()
            {
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "文件",
                ["Settings"] = "设置",
                ["Info"] = "信息",
                ["StatusInitializing"] = "初始化中...",
                ["StatusOnline"] = "网络: 在线",
                ["StatusOffline"] = "网络: 离线",
                ["StatusLocal"] = "网络: 局域网",
                ["StatusNoInternet"] = "网络: 无网络连接",
                ["StatusUndetermined"] = "网络: 未知",
                
                ["YourComputer"] = "您的电脑",
                ["StatusReady"] = "就绪",
                ["StatusStarting"] = "启动中...",
                ["StatusActive"] = "运行中",
                ["StatusWaiting"] = "等待中...",
                ["StatusConnected"] = "已连接",
                ["StatusDisconnected"] = "已断开",
                ["StatusErrorRetry"] = "错误，重试中...",
                ["HostDescription"] = "用于远程连接的唯一设备 ID，请与连接方共享。",
                ["YourId"] = "您的 ID",
                ["ProtectedByPassword"] = "受密码保护",
                ["CopyId"] = "复制 ID",
                ["ChangeId"] = "更换 ID",
                
                ["RemoteControl"] = "远程控制",
                ["ClientDescription"] = "输入远程计算机 ID 以通过加密 P2P 通道连接。",
                ["PartnerIdPlaceholder"] = "输入伙伴 ID (例如: 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "密码 (如已设置)",
                ["Connect"] = "连接",
                
                ["RecentConnections"] = "最近连接",
                ["NoRecentConnections"] = "暂无最近连接",
                ["RecentConnectionsDesc"] = "首次成功连接后将在此显示。",
                
                ["SettingsTitle"] = "设置",
                ["SectionConnection"] = "连接",
                ["SectionVideo"] = "视频",
                ["SectionSecurity"] = "安全",
                ["SectionAppearance"] = "外观与语言",
                ["SectionAbout"] = "关于",
                ["ConnectionProfile"] = "连接模式",
                ["ProfilePerf"] = "高性能",
                ["ProfileBalance"] = "均衡",
                ["ProfileQuality"] = "高质量",
                ["Port"] = "端口",
                ["ConnectionPassword"] = "连接密码",
                ["PasswordNotSet"] = "未设置",
                ["SignalingUrl"] = "信令服务器地址",
                ["CaptureMonitor"] = "捕获显示器",
                ["MonitorPrimary"] = "(主显示器)",
                ["MaxFps"] = "最大帧率",
                ["MaxResolution"] = "最大分辨率",
                ["ResNative"] = "原生",
                ["Encryption"] = "端到端加密",
                ["RequireConfirmation"] = "需要连接确认",
                ["AppTheme"] = "视觉主题",
                ["AppLanguage"] = "界面语言",
                ["Save"] = "保存",
                ["Cancel"] = "取消",
                ["ToggleOn"] = "开",
                ["ToggleOff"] = "关",
                
                ["TechInfoTitle"] = "技术架构信息",
                ["Close"] = "关闭",
                ["SecEncryption"] = "加密协议",
                ["SecNat"] = "NAT 穿透 (STUN / UDP)",
                ["SecVideoStream"] = "视频传输流",
                ["SecNetwork"] = "网络与协议",
                ["SecFeatures"] = "功能特性",
                
                ["DialogAlreadyRunningTitle"] = "程序已在运行",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROL 已在单实例模式下运行，主窗口已激活。",
                ["DialogChangeIdTitle"] = "更换 ID",
                ["DialogChangeIdContent"] = "确认更换？当前 ID 将被新的随机 ID 替代。",
                ["DialogIncomingConnTitle"] = "收到连接请求",
                ["DialogIncomingConnContent"] = "伙伴已成功连接至您的电脑，可进行画面查看与控制。",
                ["ErrorInvalidId"] = "ID 无效",
                ["ErrorInvalidIdContent"] = "请输入有效的远程计算机 ID。",
                ["ErrorConnection"] = "连接失败",
                ["ErrorConnectionContent"] = "无法建立 P2P 连接，请检查 ID、主机状态及网络。",
                ["ErrorNetwork"] = "网络错误",
                
                ["TrayRestore"] = "恢复窗口",
                ["TrayExit"] = "退出",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "应用程序已最小化至系统托盘。",
                
                ["FileManagerTitle"] = "文件管理器",
                ["LocalPc"] = "本地电脑",
                ["RemotePc"] = "远程电脑",
                ["RemotePcNotConnected"] = "远程电脑未连接",
                ["RemotePcConnectHint"] = "请先连接至远程电脑以访问文件。",
                ["ColName"] = "名称",
                ["ColSize"] = "大小",
                ["ColModified"] = "修改时间",
                ["SecureChat"] = "加密聊天",
                ["ChatPlaceholder"] = "输入消息...",
                ["Send"] = "发送",
                ["SpeedQuality"] = "画面质量",
                ["Hotkeys"] = "快捷键",
                ["AudioToggle"] = "声音: 开",
                ["Chat"] = "聊天",
                ["Disconnect"] = "关闭",
                ["SendFile"] = "发送文件...",
                ["F3View"] = "F3 查看",
                ["F5Copy"] = "F5 复制",
                ["F6Move"] = "F6 移动",
                ["F7NewFolder"] = "F7 新建文件夹",
                ["F8Delete"] = "F8 删除",
                ["F9Rename"] = "F9 重命名",
                ["CtrlRRefresh"] = "Ctrl+R 刷新"
            },
            ["ja"] = new()
            {
                ["AppTitle"] = "STORM REMOTE CONTROL",
                ["Version"] = "1.0.0",
                ["Files"] = "ファイル",
                ["Settings"] = "設定",
                ["Info"] = "情報",
                ["StatusInitializing"] = "初期化中...",
                ["StatusOnline"] = "ネットワーク: オンライン",
                ["StatusOffline"] = "ネットワーク: オフライン",
                ["StatusLocal"] = "ネットワーク: ローカル",
                ["StatusNoInternet"] = "ネットワーク: インターネット未接続",
                ["StatusUndetermined"] = "ネットワーク: 未確定",
                
                ["YourComputer"] = "お使いのPC",
                ["StatusReady"] = "準備完了",
                ["StatusStarting"] = "起動中...",
                ["StatusActive"] = "アクティブ",
                ["StatusWaiting"] = "待機中...",
                ["StatusConnected"] = "接続済み",
                ["StatusDisconnected"] = "切断済み",
                ["StatusErrorRetry"] = "エラー、再試行中...",
                ["HostDescription"] = "リモート接続用の固有IDです。接続相手に共有してください。",
                ["YourId"] = "あなたのID",
                ["ProtectedByPassword"] = "パスワード保護中",
                ["CopyId"] = "IDをコピー",
                ["ChangeId"] = "IDを変更",
                
                ["RemoteControl"] = "リモート操作",
                ["ClientDescription"] = "暗号化P2P経由で接続するために相手のIDを入力してください。",
                ["PartnerIdPlaceholder"] = "相手のIDを入力 (例: 847 291 063)",
                ["PartnerPasswordPlaceholder"] = "パスワード (設定されている場合)",
                ["Connect"] = "接続",
                
                ["RecentConnections"] = "最近の接続",
                ["NoRecentConnections"] = "接続履歴はありません",
                ["RecentConnectionsDesc"] = "接続に成功すると履歴がここに表示されます。",
                
                ["SettingsTitle"] = "設定",
                ["SectionConnection"] = "接続",
                ["SectionVideo"] = "ビデオ",
                ["SectionSecurity"] = "セキュリティ",
                ["SectionAppearance"] = "外観と言語",
                ["SectionAbout"] = "バージョン情報",
                ["ConnectionProfile"] = "接続プロファイル",
                ["ProfilePerf"] = "パフォーマンス",
                ["ProfileBalance"] = "バランス",
                ["ProfileQuality"] = "高画質",
                ["Port"] = "ポート",
                ["ConnectionPassword"] = "接続パスワード",
                ["PasswordNotSet"] = "未設定",
                ["SignalingUrl"] = "シグナリングサーバーURL",
                ["CaptureMonitor"] = "キャプチャモニター",
                ["MonitorPrimary"] = "(プライマリ)",
                ["MaxFps"] = "最大FPS",
                ["MaxResolution"] = "最大解像度",
                ["ResNative"] = "ネイティブ",
                ["Encryption"] = "暗号化",
                ["RequireConfirmation"] = "接続確認を要求",
                ["AppTheme"] = "テーマ",
                ["AppLanguage"] = "言語",
                ["Save"] = "保存",
                ["Cancel"] = "キャンセル",
                ["ToggleOn"] = "オン",
                ["ToggleOff"] = "オフ",
                
                ["TechInfoTitle"] = "技術情報",
                ["Close"] = "閉じる",
                ["SecEncryption"] = "暗号化",
                ["SecNat"] = "NAT越え (STUN / UDP)",
                ["SecVideoStream"] = "ビデオストリーム",
                ["SecNetwork"] = "ネットワークとプロトコル",
                ["SecFeatures"] = "機能一覧",
                
                ["DialogAlreadyRunningTitle"] = "既に実行中です",
                ["DialogAlreadyRunningContent"] = "STORM REMOTE CONTROLは既に実行されています。ウィンドウをアクティブ化しました。",
                ["DialogChangeIdTitle"] = "IDの変更",
                ["DialogChangeIdContent"] = "新しいIDを再生成しますか？",
                ["DialogIncomingConnTitle"] = "着信接続",
                ["DialogIncomingConnContent"] = "パートナーが接続しました。画面操作が可能です。",
                ["ErrorInvalidId"] = "無効なID",
                ["ErrorInvalidIdContent"] = "有効なIDを入力してください。",
                ["ErrorConnection"] = "接続エラー",
                ["ErrorConnectionContent"] = "P2P接続を確立できませんでした。",
                ["ErrorNetwork"] = "ネットワークエラー",
                
                ["TrayRestore"] = "復元",
                ["TrayExit"] = "終了",
                ["TrayBalloonTitle"] = "STORM REMOTE CONTROL",
                ["TrayBalloonText"] = "タスクトレイに最小化されました。",
                
                ["FileManagerTitle"] = "ファイルマネージャー",
                ["LocalPc"] = "ローカルPC",
                ["RemotePc"] = "リモートPC",
                ["RemotePcNotConnected"] = "リモートPC未接続",
                ["RemotePcConnectHint"] = "リモートPCに接続してファイルを表示します。",
                ["ColName"] = "名前",
                ["ColSize"] = "サイズ",
                ["ColModified"] = "更新日時",
                ["SecureChat"] = "暗号化チャット",
                ["ChatPlaceholder"] = "メッセージ...",
                ["Send"] = "送信",
                ["SpeedQuality"] = "画質設定",
                ["Hotkeys"] = "ショートカット",
                ["AudioToggle"] = "音声: オン",
                ["Chat"] = "チャット",
                ["Disconnect"] = "閉じる",
                ["SendFile"] = "ファイルを送信...",
                ["F3View"] = "F3 表示",
                ["F5Copy"] = "F5 コピー",
                ["F6Move"] = "F6 移動",
                ["F7NewFolder"] = "F7 新規フォルダ",
                ["F8Delete"] = "F8 削除",
                ["F9Rename"] = "F9 名前の変更",
                ["CtrlRRefresh"] = "Ctrl+R 更新"
            }
        };

        public static string Get(string key)
        {
            if (Strings.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            {
                return val;
            }
            if (Strings.TryGetValue("ru", out var ruDict) && ruDict.TryGetValue(key, out var ruVal))
            {
                return ruVal;
            }
            if (Strings.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enVal))
            {
                return enVal;
            }
            return key;
        }

        public static string FormatDate(DateTime dt)
        {
            return dt.ToString("dd.MM.yyyy");
        }

        public static string FormatTime(DateTime dt)
        {
            return dt.ToString("HH:mm");
        }

        public static string FormatDateTime(DateTime dt)
        {
            return dt.ToString("dd.MM.yyyy HH:mm");
        }
    }
}
